### ISSUE TITLE
Erro decoding

### ISSUE THREAD

**Issue by franklupo** [axcheron/ptexplorer#2]
This error appears on execution:

```python
~ ./ptexplorer.py -d aaa.pka pippo.xml
[*] Opening Packet Tracer file 'aaa.pka'
[*] File size compressed = 222995 bytes
[*] File size uncompressed = 471679052 bytes
[*] Writing XML to 'pippo.xml'
Traceback (most recent call last):
  File "./ptexplorer.py", line 81, in <module>
    ptfile_decode(args.infile, args.outfile)
  File "./ptexplorer.py", line 34, in ptfile_decode
    f.write(zlib.decompress(out[4:]))
zlib.error: Error -3 while decompressing data: incorrect header check
````

Same error on **pkt** or **pka**

Best regards

**Comment by Mishin870** [comment]
Hello! Try packet tracer version bellow 5
#1

**Comment by ferib** [comment]
What version of Packet Tracer are you using, @franklupo? this tool seems to be made for version 5 and the current version of Packet Tracer is 7.

@axcheron I noticed that the XOR decoded output doesn't give the same results like the one shown in the readme.md.

**Comment by franklupo** [comment]
Hi 
I using 7 version

Best regards

**Comment by ferib** [comment]
@franklupo According to my research there are 2 more stages of encoding added to the algorithm.
The first one is still the reverse XOR which seems slightly change, the second one is unknown to me, the third one unpacks the final state to the zlib byte buffer (with 4byte size prefix) and the fourth stage extracts the zlib buffer to the final XML format you are hoping for.

The version I tested on looks like this:
```xml
<PACKETTRACER5_ACTIVITY>
 <VERSION>7.2.1.0218</VERSION>
 <PACKETTRACER5>
  <VERSION>7.2.1.0218</VERSION>
  <PIXMAPBANK>
...
```

**Comment by franklupo** [comment]
can you make a fix?

**Comment by ferib** [comment]
> can you make a fix?

Well yes, but actually no.
I am not sure what you want to achieve.

**Comment by franklupo** [comment]
HI,
I would like to create a Packet Tracer file from my C# application. I have no idea what xml looks like but I thought that by reverse engignering I would understand how the file is structured.

Best reagrds

**Comment by ferib** [comment]
@franklupo Then I have bad news for you.
The latest version of Packet Tracers uses four stages of decoding (rather than the two seen in this repo)

Sadly, there seems to be no other project that I am aware of that are capable of what you want.
Sounds like your last hope is to reverse engineer PacketTracer7 and look into how the packing/unpacking is done exactly so you can then re-create the process.

**Comment by rooney28** [comment]
Hi,

I must use packet tracer 7.2 in my project and I have the same issue.

Please if there is any solution to fix the error

Regards

**Comment by mircodz** [comment]
For anyone interested I have managed to reverse the new encoding/decoding algorithm and have written a small tool to convert pka/pkt files into xml. You can find it [here](https://github.com/mircodezorzi/pka2xml).

**Comment by ferib** [comment]
@mircodezorzi Congrats, you naild it!
I was just wrapping up my blog post and about to publish it, now I feel defeated 😅

**Comment by rooney28** [comment]
@mircodezorzi thank you a lot, I am trying to run it but I am using windows 10 and I can not setup the code you provide. any idea?

@ferib for sure I like to know your solution

Regards

**Comment by mircodz** [comment]
@rooney28 The code isn't platform specific. Make sure you have installed cryptopp and zlib and you should be ok.

**Comment by rooney28** [comment]
@mircodezorzi do you mean that I have to download cryptopp from https://github.com/weidai11/cryptopp
and zlib from https://zlib.net/
then open the code using visual studio and build it?

Thank you in advanced
Regards

**Comment by ferib** [comment]
@rooney28 its only a matter of time until someone builds a web-based tool for it.
in fact, @mircodezorzi already has his stuff deployed into the cloud check it out: https://mircodezorzi.github.io/doc/pka2xml-aws/

I was also working on a similar tool like that which comes with unique features that Packet Tracer itself is lacking, such as, converting older versions (version 5) to whatever version there is.

**Comment by rooney28** [comment]
@ferib I follow the instruction by @mircodezorzi from https://mircodezorzi.github.io/doc/pka2xml-aws/
I am using windows 10
I have started by Installing the C++ Lambda Runtime so I install git bash and cmake on windows 10
First 5 lines worked ok "for sure I changed paths but I don't know what -DCMAKE_INSTALL_PREFIX=$HOME/pka2xml/lambda-runtime should be"
Now I want to run make && make install but it gives me an error "make: *** No targets specified and no makefile found.  Stop."

I am sorry, but it's the first time I install and build a project using git, cmake....

Regards

**Comment by ferib** [comment]
@rooney28 I didn't mean you should install and build it.
I mean that you can just use the little demo he hosts there on his blog post, it's literally next to the intro.

**Comment by rooney28** [comment]
@ferib  thanks for your time

I used the demo and it's great
but I need to build it on my pc so I can use it as part of my project in faculty 

Regards

**Comment by franklupo** [comment]
Is it possible to have the C # code to create a library?
Thanks

**Comment by ferib** [comment]
@franklupo that is possible, I will release my C# project to manipulate .pka files in a couple of weeks.

**Comment by mircodz** [comment]
@franklupo 
> Is it possible to have the C # code to create a library?
> Thanks

I'm no C# expert but from what I could read from [here](https://www.codeproject.com/Articles/2593/A-C-implementation-of-the-Twofish-cipher) the .NET standard library seems to provide a fairly simple way to use the Twofish cipher, you could port the C++ code in a matter of 10-15 minutes 😉

**Comment by ferib** [comment]
> I'm no C# expert but from what I could read from here the .NET standard library seems to provide a fairly simple way to use the Twofish cipher, you could port the C++ code in a matter of 10-15 minutes 😉

@mircodezorzi hah, thats the exact same library I have used for my project, here is a snipper for whoever needs it:

```cs
public bool unpackStageTwo()
        {
            Twofish twofish = new Twofish()
            {
                Mode = System.Security.Cryptography.CipherMode.CBC,
                Key = new byte[] { 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89, 0x89 },
                IV = new byte[] { 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10 }
            };

            ICryptoTransform decrypt = twofish.CreateDecryptor();
            System.IO.MemoryStream msD = new System.IO.MemoryStream();
            CryptoStream cryptostreamDecr = new CryptoStream(msD, decrypt, CryptoStreamMode.Write);

            cryptostreamDecr.Write(this.Buffer, 0, this.Buffer.Length);
            cryptostreamDecr.Close();

            byte[] tmp = msD.GetBuffer();
            Console.WriteLine(tmp.Length);
            for (int i = 0; i < this.Buffer.Length; i++)
                this.Buffer[i] = tmp[i];

            return true;
        }
```
